### ISSUE TITLE
Account creation fails with "adresse mail est déjà utilisée"

### ISSUE THREAD

**Issue by r0one** [simde-utc/portail#293] opened 2019-11-10 18:02 UTC
![image](https://user-images.githubusercontent.com/18699331/68548374-7e0a7080-03ec-11ea-9b28-b1a2d169d735.png)

**Comment by NastuzziSamy** [comment] 2019-11-10 18:49
What do you mean ? What was the full process ?

**Comment by r0one** [comment] 2019-11-11 08:19
Well just try to create an account and you'll get the same error.

**Comment by MercierCorentin** [comment] 2019-12-01 01:24
I cannot reproduce the error, i've created several accounts. Closing until next time if there is one.

**Closed as completed by MercierCorentin** 2019-12-01 01:24 UTC
Labels: bug, UX
